project:
  type: website

website:
  navbar:
    title: "Analyzing Impact of COVID-19 on NYC School Populations"
    left:
      - text: "Home"
      - href: index.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Exploratory data analysis"
        href: explore.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "Report"
        href: report.qmd
      - text: "Appendices"
        href: appendices.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: true
